import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BarChart3, RefreshCw } from 'lucide-react'
import { fetchFunnel, fetchLeads, type LeadItem } from '@/api/enterprise'

const labels: Record<string, string> = { new: '新线索', contacting: '跟进中', qualified: '已合格', signed: '已签约', lost: '已流失' }
const colors: Record<string, string> = { new: '#2f80ed', contacting: '#d8913d', qualified: '#7856c7', signed: '#2e9d68', lost: '#98a2b3' }

export function EnterpriseBoardPage() {
  const [funnel, setFunnel] = useState<Record<string, number>>({})
  const [leads, setLeads] = useState<LeadItem[]>([])
  const [loading, setLoading] = useState(true)
  async function load() { setLoading(true); try { const [funnelData, leadData] = await Promise.all([fetchFunnel(), fetchLeads()]); setFunnel(funnelData); setLeads(leadData.items) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const countryItems = useMemo(() => Object.entries(leads.reduce<Record<string, number>>((acc, item) => { const country = item.intended_country || '未填写'; acc[country] = (acc[country] || 0) + 1; return acc }, {})).sort((a, b) => b[1] - a[1]), [leads])
  const maxCountry = Math.max(1, ...countryItems.map(([, value]) => value))
  return <section className="content-page"><header className="page-heading"><div><div className="eyebrow"><BarChart3 size={14} /> CUSTOMER BOARD</div><h1>客户看板</h1><p>用一眼看清当前线索状态和意向分布。</p></div><button className="ghost-button" onClick={() => void load()}><RefreshCw size={16} className={loading ? 'spin' : ''} />刷新</button></header><div className="board-metrics"><div><span>客户总数</span><strong>{leads.length}</strong></div><div><span>已签约</span><strong>{funnel.signed || 0}</strong></div><div><span>签约占比</span><strong>{leads.length ? `${Math.round(((funnel.signed || 0) / leads.length) * 100)}%` : '0%'}</strong></div></div><div className="board-grid"><section className="panel-surface board-card"><div className="panel-heading"><div><div className="eyebrow">FUNNEL</div><h2>线索漏斗</h2></div><ArrowUpRight size={17} /></div><div className="funnel-chart">{Object.entries(labels).map(([key, label]) => { const value = funnel[key] || 0; const max = Math.max(1, ...Object.keys(labels).map((item) => funnel[item] || 0)); return <div className="funnel-row" key={key}><div className="funnel-row-label"><span>{label}</span><b>{value}</b></div><div className="funnel-track"><i style={{ width: `${Math.max(value ? 8 : 0, (value / max) * 100)}%`, background: colors[key] }} /></div></div> })}</div></section><section className="panel-surface board-card"><div className="panel-heading"><div><div className="eyebrow">COUNTRY MIX</div><h2>意向国家</h2></div><ArrowUpRight size={17} /></div><div className="bar-list">{countryItems.map(([label, value]) => <div className="bar-item" key={label}><div><span>{label}</span><b>{value}</b></div><div className="bar-track"><i style={{ width: `${(value / maxCountry) * 100}%` }} /></div></div>)}{!countryItems.length && <div className="empty-inline">还没有客户意向</div>}</div></section></div><section className="panel-surface board-table"><div className="section-title"><div><div className="eyebrow">LEADS</div><h2>意向客户</h2></div><span>{leads.length} 条</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>客户</th><th>联系方式</th><th>意向国家</th><th>学历</th><th>状态</th><th>负责人</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id}><td><strong>{lead.customer_name}</strong></td><td>{lead.contact_info || '—'}</td><td>{lead.intended_country || '—'}</td><td>{lead.education_level || '—'}</td><td><span className="status-badge"><i />{lead.status_text}</span></td><td>{lead.owner_name || '—'}</td></tr>)}{!leads.length && <tr><td colSpan={6}><div className="empty-cell">没有客户数据</div></td></tr>}</tbody></table></div></section></section>
}
