import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Building2, Mail, MapPin, Phone, RefreshCw } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { fetchCompany, fetchOrgs } from '@/api/enterprise'

type Org = { id: number; org_name: string; parent_id: number | null; children?: Org[] }
function tree(items: Org[]) { const map = new Map(items.map((item) => [item.id, { ...item, children: [] as Org[] }])); const roots: Org[] = []; items.forEach((item) => { const node = map.get(item.id); if (!node) return; if (item.parent_id && map.has(item.parent_id)) map.get(item.parent_id)!.children!.push(node); else roots.push(node) }); return roots }
function OrgList({ nodes, level = 0 }: { nodes: Org[]; level?: number }) { return <div>{nodes.map((node) => <div key={node.id} className="org-node" style={{ paddingLeft: level * 20 }}><span className="org-dot" />{node.org_name}{node.children?.length ? <OrgList nodes={node.children} level={level + 1} /> : null}</div>)}</div> }

export function EnterpriseCompanyPage() {
  const navigate = useNavigate(); const [card, setCard] = useState<Record<string, unknown>>({}); const [orgs, setOrgs] = useState<Org[]>([]); const [loading, setLoading] = useState(true)
  async function load() { setLoading(true); try { const [company, orgList] = await Promise.all([fetchCompany(), fetchOrgs()]); setCard(company); setOrgs(orgList as Org[]) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const business = (card.business as string[]) || []; const departments = (card.departments as string[]) || []; const orgTree = useMemo(() => tree(orgs), [orgs])
  return <section className="content-page"><header className="page-heading"><div><div className="eyebrow"><Building2 size={14} /> COMPANY PROFILE</div><h1>公司简介</h1><p>{String(card.full_name || '粤教服务')}（{String(card.short_name || '企业信息')}）</p></div><button className="ghost-button" onClick={() => navigate('/enterprise')}><ArrowRight size={16} />去对话里问</button></header><section className="company-hero panel-surface"><div className="company-seal"><Building2 size={28} /></div><div><span className="eyebrow">ABOUT US</span><h2>{String(card.intro || '广东省教育服务有限公司')}</h2><p>{String(card.transfer || '')}</p></div></section><div className="info-grid-react"><Info icon={<span>◎</span>} label="使命" value={String(card.mission || '—')} /><Info icon={<span>✦</span>} label="价值观" value={String(card.values || '—')} /><Info icon={<Phone size={15} />} label="电话" value={String(card.phone || '—')} extra={String(card.email || '')} /><Info icon={<MapPin size={15} />} label="地址" value={String(card.address || '—')} extra={String(card.site || '')} /></div><div className="company-columns"><section className="panel-surface content-card"><div className="section-title"><h2>主营业务</h2><span>{business.length} 项</span></div><div className="tag-cloud">{business.map((item) => <span key={item}>{item}</span>)}{!business.length && <span>暂无业务信息</span>}</div></section><section className="panel-surface content-card"><div className="section-title"><h2>组织架构</h2><span>{orgs.length} 个组织</span></div>{orgTree.length ? <OrgList nodes={orgTree} /> : <div className="tag-cloud">{departments.map((item) => <span key={item}>{item}</span>)}</div>}</section></div>{loading && <div className="loading-overlay"><RefreshCw size={18} className="spin" />正在加载</div>}</section>
}
function Info({ icon, label, value, extra }: { icon: React.ReactNode; label: string; value: string; extra?: string }) { return <article className="info-card-react"><div className="info-icon">{icon}</div><div><small>{label}</small><strong>{value}</strong>{extra && <span><Mail size={13} />{extra}</span>}</div></article> }
